### PR TITLE
fix html structure

### PR DESCRIPTION
**Pull request by t-schroeder**
There are too many closing tags for the "qtext" div. The consequence is that when attempting a quiz the page layout is broken.

I can create an issue and attach a screenshot, sample question if necessary.

### CODE REVIEW

**Comment by marcusgreen** [comment]
Could you give me steps to reproduce this. I have a unit test to check the divs are evenly closed here
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/f5533b7922389be95b1782bd9b3cf4c2acfd18e3/tests/walkthrough_test.php#L514

**Comment by t-schroeder** [comment]
Nevermind, I just realized I was using version 2021063001 of your plugin. With your fix for #76 you already fixed the problem I was trying to fix here.

The empty div tags for "qtext" and "answeroptions" (which should be start tags instead) still technically create wrong HTML, but seems like most browsers are robus enough to handle that.

**Comment by marcusgreen** [comment]
When I worked on that I was looking for a tool to add proper html validation into the unit tests, but (surprisingly) I couldn't find anything, so settled on my crude checking that there was an even number of start and end divs. I would rather my code put out correct HTML even if browsers do tolerate errors.  I appreciate your input and will look at your other issue as soon as I can.

**Comment by marcusgreen** [comment]
I have been running the rendered output through this validator
https://validator.w3.org/nu/#textarea
And it is a bit of a mess. I will work on ensuring the output is more compliant in future versions.

**Pull request closed without merging**
