### PR TITLE
Fix question compatibility with Dark theme

### PR DESCRIPTION
**Pull request by bi1101**

### CODE REVIEW

**Comment by marcusgreen** [comment]
Is there a theme or setting I can test this against?

**Comment by bi1101** [comment]
There is a Dark theme in the Moodle App that you can try.
Yes I believe that is the theme that I was talking about

**Comment by marcusgreen** [comment]
Thank you, I will set it up and have a look. Thank you for the feedback.

**Comment by marcusgreen** [comment]
Yes, the text is almost unreadable in dark mode. I will test out your code.

**Comment by marcusgreen** [comment]
I like to add a credit to the changelog file when I release to the moodle.org plugins database
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/changelog.md
What name should put against this change or should I use bi1101?

**Comment by bi1101** [comment]
Oh yes!  Thank you that's very nice of you, bi1101 is good.

**Pull request merged**
